use std::fmt::Write;

use sdkt_core::{
    contract::{ContractFunction, ContractSpec, Type},
    ClientGenError,
};

/// Options controlling Rust client generation.
#[derive(Debug, Clone)]
pub struct GenerateOptions {
    /// Skip unsupported functions instead of returning an error.
    pub skip_unsupported: bool,
}

impl Default for GenerateOptions {
    fn default() -> Self {
        Self {
            skip_unsupported: false,
        }
    }
}

/// Generate a deterministic Rust client module.
pub fn generate_client(spec: &ContractSpec) -> Result<String, ClientGenError> {
    generate_client_with_options(spec, &GenerateOptions::default())
}

/// Generate a deterministic Rust client module with custom options.
pub fn generate_client_with_options(
    spec: &ContractSpec,
    options: &GenerateOptions,
) -> Result<String, ClientGenError> {
    let (supported, skipped) = collect_supported_functions(spec, options)?;

    let mut output = String::new();

    write_header(&mut output, &skipped);

    if spec.functions.is_empty() {
        write_empty_contract(&mut output);
        return Ok(output);
    }

    if supported.is_empty() {
        write_no_supported_functions(&mut output);
        return Ok(output);
    }

    write_contract_functions(&mut output, &supported);

    Ok(output)
}

/// Collected supported and skipped contract functions.
type CollectedFunctions<'a> = (
    Vec<&'a ContractFunction>,
    Vec<(&'a ContractFunction, ClientGenError)>,
);

/// Separate supported functions from skipped functions.
fn collect_supported_functions<'a>(
    spec: &'a ContractSpec,
    options: &GenerateOptions,
) -> Result<CollectedFunctions<'a>, ClientGenError> {
    let mut supported = Vec::new();
    let mut skipped = Vec::new();

    for function in &spec.functions {
        match check_supported(function) {
            Ok(()) => supported.push(function),
            Err(error) if options.skip_unsupported => {
                skipped.push((function, error));
            }
            Err(error) => return Err(error),
        }
    }

    Ok((supported, skipped))
}

/// Check whether a contract function can be represented by the generated client.
fn check_supported(function: &ContractFunction) -> Result<(), ClientGenError> {
    for input in &function.inputs {
        check_supported_type(&input.type_)?;
    }

    check_supported_type(&function.output)?;

    Ok(())
}

/// Check whether a contract type is supported by the generated client.
fn check_supported_type(ty: &Type) -> Result<(), ClientGenError> {
    match ty {
        Type::U32
        | Type::U64
        | Type::U128
        | Type::I32
        | Type::I64
        | Type::I128
        | Type::Bool
        | Type::Address
        | Type::Bytes
        | Type::String
        | Type::Symbol
        | Type::Void => Ok(()),

        _ => Err(ClientGenError::UnsupportedType(format!("{ty:?}"))),
    }
}

/// Write the generated file header.
fn write_header(
    output: &mut String,
    skipped: &[(&ContractFunction, ClientGenError)],
) {
    output.push_str(
        "//! Auto-generated Soroban contract client.\n\
         //!\n\
         //! DO NOT EDIT THIS FILE MANUALLY.\n\n",
    );

    if !skipped.is_empty() {
        output.push_str("// Skipped unsupported functions:\n");

        for (function, error) in skipped {
            writeln!(
                output,
                "// - {}: {}",
                function.name,
                error
            )
            .expect("writing to String cannot fail");
        }

        output.push('\n');
    }
}

/// Write an empty contract implementation.
fn write_empty_contract(output: &mut String) {
    output.push_str(
        "/// Generated client for an empty contract.\n\
         pub struct Client;\n",
    );
}

/// Write a contract implementation when no functions are supported.
fn write_no_supported_functions(output: &mut String) {
    output.push_str(
        "/// Generated client containing no supported contract functions.\n\
         pub struct Client;\n",
    );
}

/// Write the client structure and function declarations.
fn write_contract_functions(
    output: &mut String,
    functions: &[&ContractFunction],
) {
    output.push_str("/// Generated Soroban contract client.\n");
    output.push_str("pub struct Client;\n\n");

    output.push_str("impl Client {\n");

    for function in functions {
        write_function(output, function);
    }

    output.push_str("}\n");
}

/// Write an individual contract function.
fn write_function(output: &mut String, function: &ContractFunction) {
    writeln!(
        output,
        "    /// Client method for `{}`.",
        function.name
    )
    .expect("writing to String cannot fail");

    writeln!(
        output,
        "    pub fn {}(&self) {{",
        function.name
    )
    .expect("writing to String cannot fail");

    output.push_str("        // TODO: invoke the Soroban contract function.\n");
    output.push_str("    }\n\n");
}
