[package]
name = "sdkt-storage"
version = "0.6.0-alpha"
edition = "2021"
description = "Storage monitoring utility and TTL extensions logic for Soroban contracts."
repository = "https://github.com/naninu123/soroban-devkit"
homepage = "https://github.com/naninu123/soroban-devkit"
readme = "../../README.md"
keywords = ["soroban", "stellar", "sdk", "toolkit", "blockchain"]
categories = ["development-tools", "network-programming"]
license = "MIT"

[dependencies]
directories = "5.0.1"
sdkt-rpc = { version = "0.6.0-alpha", path = "../sdkt-rpc" }
sdkt-wasm = { version = "0.6.0-alpha", path = "../sdkt-wasm" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }

[dev-dependencies]
tempfile = "3"
