[package]
name = "sdkt-audit-example-rule"
description = "Example sdkt-audit plugin rule (reference/documentation only)."
authors.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "../../README.md"
keywords = ["soroban", "stellar", "sdk", "toolkit", "audit"]
categories = ["development-tools"]

[dependencies]
sdkt-audit = { version = "1.0.0", path = "../sdkt-audit" }
